### ISSUE TITLE
Pulling T-Bill rates from FRED

### ISSUE THREAD

**Issue by nickmoen** [nickmoen/CAPM#3]
I can't seem to figure out how to isolate the most recent weekly rate of a T-Bill from FRED for a risk free rate. Any insight would be a tremendous help.

**Comment by Matt-Brigida** [comment]
Try:

```
t <- getSymbols("TB1YR", src = "FRED", auto.assign = FALSE)
t[length(t)]
```

**Comment by nickmoen** [comment]
This worked perfectly. Thank you.
