### ISSUE TITLE
Publishing the updated app

### ISSUE THREAD

**Issue by nickmoen** [nickmoen/CAPM#4]
There seems to be an error on the app's webpage since I updated it with the new code:

https://nickmoen.shinyapps.io/CAPM

Not sure what it wants. Any ideas?

**Comment by Matt-Brigida** [comment]
This might be related to sites (such as FRED) switching to https.  See some possible solutions here:

>  http://stackoverflow.com/questions/31188023/quantmod-error-cannot-open-url

**Comment by nickmoen** [comment]
Found the solution. 

adding "options(download.files.method="curl")" seemed to do the trick.

Thanks.
